config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'static_pages#home'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  get  'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  resources :users, only: %i[new create destroy]
  resources :time_attacks, only: %i[index]
  resources :lessons, only: %i[index show]
  resources :user_time_attacks, only: %i[index create]
  resources :password_resets, only: %i[new create edit update]
  # resources :contacts, only: %i[new create]
  resource :profile, only: %i[show edit update]
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  skip_before_action :require_login

  def index
    @shortcut_keys = ShortcutKey.new.lessons_shortcut_keys(request.os)
    @shortcut_keys_json = @shortcut_keys.to_json
  end

  def show
    @shortcut_key = ShortcutKey.find(params[:id])
    @shortcut_key_json = @shortcut_key.to_json
    @os = set_os_type
  end
end

app/views/lessons/index.html.slim
- content_for(:title, t('.title'))
h1.my-3 = t '.title'
.container
  table.table.table-striped
    thead.bg-vs-blue
      tr
        th.text-center scope="col"
          p = t 'activerecord.models.shortcut_key'
        th.text-left scope="col"
          p = t '.overview'
    tbody
      - @shortcut_keys.each do |shortcut_key|
        tr
          td.text-center
            p
              = shortcut_key.display_key
          td.text-left
            p
              = link_to shortcut_key.question, lesson_path(shortcut_key.id)

app/views/lessons/show.html.slim
.container.mt-3.text-center
  - if @os == 'Mac'
    .mx-auto
      p.alert.alert-warning.bg-vs-blue
        | コマンド記号 :
        span ⌘ Command / ⌥ Option / ⇧ Shift / ⌃ Control / Delete Fn + ⌫
  .card.mt-3
    .card-header.bg-vs-blue
      p = @shortcut_key.question
    ul.list-group.list-group-flush
      li.list-group-item.text-center.bg-vs-dark
        p = "ショートカットキー : #{@shortcut_key.display_key}"
      li.list-group-item.text-center.bg-vs-dark
        p
          | 入力中コマンド :
          span#command
    .card.bg-vs-dark
      = image_tag @shortcut_key.image_url, class: "bd-placeholder-img card-img-top col-12 mx-auto"
  = link_to "戻る", lessons_path, class: "btn btn-lg btn-primary my-3 mx-auto bg-vs-blue"

input.shortcut_keys_json name="arr_json" type="hidden" value="#{@shortcut_key_json}"
input.os name="os" type="hidden" value="#{@os}"

= javascript_pack_tag 'lesson'