config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'static_pages#home'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  get  'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  resources :users, only: %i[new create destroy]
  resources :time_attacks, only: %i[index]
  resources :lessons, only: %i[index show]
  resources :user_time_attacks, only: %i[index create]
  resources :password_resets, only: %i[new create edit update]
  # resources :contacts, only: %i[new create]
  resource :profile, only: %i[show edit update]
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to root_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_back_or_to root_path, success: t('.success')
  end
end

app/views/user_sessions/new.html.slim
- content_for(:title, t('.title'))
.container.mt-3
  .row
    .col-md-10.offset-md-1.col-lg-8.offset-lg-2
      h1.my-3
        = t '.title'
      = form_with url: login_path, method: :post, local: true do |f|
        .form-group
          = f.label :email, t('activerecord.attributes.user.email')
          = f.text_field :email, class: "form-control"
        .form-group
          = f.label :password, User.human_attribute_name(:password)
          = f.password_field :password, class: "form-control"
        .actions
          = f.submit (t 'defaults.login'), class: "btn btn-primary"
        .text-center
          = link_to (t '.to_register_page'), new_user_path
          span = '/'
          = link_to (t '.password_forget'), new_password_reset_path