config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'static_pages#home'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'

  get  'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  resources :users, only: %i[new create destroy]
  resources :time_attacks, only: %i[index]
  resources :lessons, only: %i[index show]
  resources :user_time_attacks, only: %i[index create]
  resources :password_resets, only: %i[new create edit update]
  # resources :contacts, only: %i[new create]
  resource :profile, only: %i[show edit update]
end

app/views/layouts/_footer.html.slim
footer.footer.mt-auto.py-3.bg-vs-dark
  .container
    span.text-muted
      | © #{t('defaults.app_name')}
      ul.list-unstyled.text-small.my-auto
        li
          = link_to link_to t('static_pages.home.title'), root_path, class: "text-muted"
        li
          = link_to link_to t('static_pages.terms.title'), terms_path, class: "text-muted"
        li
          = link_to link_to t('static_pages.privacy.title'), privacy_path, class: "text-muted"

app/views/layouts/_header.html.slim
header
  nav.navbar.navbar-expand-md.navbar-dark.bg-vs-dark
    = link_to t('defaults.app_name'), root_path, id: "logo", class: "navbar-brand"
    button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"]
      span.navbar-toggler-icon
    #navbarCollapse.collapse.navbar-collapse
      ul.navbar-nav.mr-auto
        li.nav-item
          = link_to t('static_pages.home.title'), root_path, class: "nav-link"
        li.nav-item
          = link_to t('time_attacks.index.title'), time_attacks_path, class: "nav-link"
        li.nav-item
          = link_to t('lessons.index.title'), lessons_path, class: "nav-link"
      .mt-2.mt-md-0
        ul.navbar-nav.mr-auto
          - if logged_in?
            li.nav-item
              = link_to t('profiles.show.title'), profile_path, class: "nav-link"
            li.nav-item
              = link_to t('defaults.logout'), logout_path, class: "nav-link", method: :delete
            / li.nav-item
            /   = link_to t('contacts.new.title'), new_contact_path, class: "nav-link"
          - else
            li.nav-item
              = link_to t('users.new.title'), new_user_path, class: "nav-link"
            li.nav-item
              = link_to t('defaults.login'), login_path, class: "nav-link"
            / li.nav-item
            /   = link_to t('contacts.new.title'), new_contact_path, class: "nav-link"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = page_title(yield(:title))
    = csrf_meta_tags
    = csp_meta_tag
    = display_meta_tags(default_meta_tags)
    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
    = javascript_include_tag 'manifest'
    = analytics_init if Rails.env.production?
  body
    = render 'layouts/header'
    = render 'shared/flash_message'
    = yield
    = render 'layouts/footer'